apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: update-currency-job
spec:
  schedule: "56 0,2,4,6,8,10,12,14,16,18,20,22 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: update-currency
            image: aloyoga/sync-files-job:1
            env:
            - name: "SPACES_NAME"
              value: "alo-geo-distribution"
            - name: "SPACES_KEY"
              value: "2QR5O3GEZWXTFSWPOVTC"
            - name: "SPACES_SECRET"
              value: "UqkUkzTrKdRUvE+1717RjNSVbni6N2M/TmtSNaon130"
            - name: "SPACES_ENDPOINT"
              value: "nyc3.digitaloceanspaces.com"
            - name: "SYNC_FILES_1"
              value: "exchangeRates.json::https://fcsapi.com/api-v2/forex/base_latest?symbol=USD&type=forex&access_key=LMW4kIieolOPNEJnL20t19dmWhZ3AsaM4pjqLjKDUuxRCyHI"
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: update-geo-job
spec:
  schedule: "0 12 * * 6"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: update-geo
            image: aloyoga/sync-files-job:1
            env:
            - name: "SPACES_NAME"
              value: "alo-geo-distribution"
            - name: "SPACES_KEY"
              value: "2QR5O3GEZWXTFSWPOVTC"
            - name: "SPACES_SECRET"
              value: "UqkUkzTrKdRUvE+1717RjNSVbni6N2M/TmtSNaon130"
            - name: "SPACES_ENDPOINT"
              value: "nyc3.digitaloceanspaces.com"
            - name: "SYNC_FILES_1"
              value: "GeoLite2-City.tar.gz::https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=jCGk7j7sV0jtYnGa&suffix=tar.gz"
          restartPolicy: OnFailure
